# Generated by Django 3.2.12 on 2022-03-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='product_api.remise'),
        ),
    ]
