# Generated by Django 3.2.12 on 2022-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_alter_product_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
    ]
