# Generated by Django 3.2.12 on 2022-03-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_product_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='remise',
        ),
        migrations.AddField(
            model_name='remise',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_api.product'),
        ),
    ]
