# Generated by Django 3.2.12 on 2022-03-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0005_alter_remise_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantite',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
