# Generated by Django 3.2.12 on 2022-03-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0002_auto_20220331_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
