# Generated by Django 3.2.12 on 2022-03-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0003_auto_20220331_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='finalPrix',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
