# Generated by Django 3.2.12 on 2022-04-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0005_auto_20220401_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonde',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
