# Generated by Django 3.2.12 on 2022-04-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0006_product_quantite'),
        ('cart_api', '0006_alter_commonde_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_api.product'),
        ),
    ]
